### ISSUE TITLE
No iframe scrolling in IOS devices 

### ISSUE THREAD

**Issue by nhead** [artsy/scroll-frame#23]
The iframe isn't scrolling, but the rest of the page behind yes.
Is there any solution for this issue?

I tried in ipod and ipad mini / Safari & Chrome Browser.

**Comment by nhead** [comment]
I think I've solved. I did a few test and works well. 
I made a fork: https://github.com/nhead/scroll-frame

**Comment by craigspaeth** [comment]
Very cool! I'll take a look at your fork soon and see if we can merge it into master. Thanks for looking into this!

**Comment by craigspaeth** [comment]
Thank you! Fixed in https://github.com/artsy/scroll-frame/pull/25
