### ISSUE TITLE
duplicate scrollbar in Firefox

### ISSUE THREAD

**Issue by adick** [artsy/scroll-frame#24]
Firefox shows 2 scrollbars when the detail page is open:

![scroll-frame](https://cloud.githubusercontent.com/assets/3079024/6128887/15a5abcc-b13a-11e4-9083-bab63aac8a96.jpg)

My Firefox version is 35.0.1

I discovered that the `isWebkit` condition is the problem. 
Setting it to true or removing the if conditions solves the problem. 

````
(function() {

  // var isWebkit = navigator.userAgent.match('WebKit');
  var isWebkit = true;
````

**Comment by craigspaeth** [comment]
Interesting! Likely [this line](https://github.com/artsy/scroll-frame/blob/master/scroll-frame.js#L59) where we add `overflow: hidden` for only webkit needs to be lifted for all browsers. Thanks for reporting!

**Comment by craigspaeth** [comment]
Thank you! Fixed in https://github.com/artsy/scroll-frame/pull/25
