### ISSUE TITLE
iPhone iOS Safari Browser doesn't Scroll and Freezes

### ISSUE THREAD

**Issue by jayrei** [artsy/scroll-frame#32]
I've tried everything to fix including updating the scroll-frame files but the Safari browser in iOS iPhone still won't scroll and freezes when the iframe in position. I've tried adding the `-webkit-overflow-scrolling:touch` as well.

**Comment by kamaldhariyal** [comment]
Hi... can you share me the script. Does it work in latest version of siri. Is it freeze it.??
